name: DayNightPvP
version: '${project.version}'
author: needkg
main: org.callv2.daynightpvp.DayNightPvP
api-version: '1.16'
softdepend: [PlaceholderAPI, GriefPrevention, Vault, WorldGuard]
load: POSTWORLD

commands:
  daynightpvp:
    description: "Show all available commands."
    usage: "/dnp"
    aliases: [dnp]
    permission: dnp.admin
  daynightpvp reload:
    description: "Reload the plugin"
    usage: "/dnp reload"
    aliases: [dnp reload]
    permission: dnp.admin

permissions:
  dnp.admin:
    description: Ensures access to all DNP commands.
    default: op
  dnp.bypasspvp:
    description: Allows the user to engage in combat even during the day.
    default: false