name: DayNightPvP
version: '${project.version}'
author: 'needkg'
main: com.needkg.daynightpvp.DayNightPvP
api-version: '1.16'
softdepend: [PlaceholderAPI, GriefPrevention, Vault]
commands:
  dnp:
    description: "Open the gui."
    aliases: [ daynightpvp ]
  dnp reload:
    description: "Reload plugin"
    aliases: [ daynightpvp reload]