name: Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up BuildTools
        run: wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install CraftBukkit
        run: |
          java -jar BuildTools.jar --rev 1.21 --compile craftbukkit --remapped

      - name: Compile DayNightPvP
        run: mvn clean package install --batch-mode --update-snapshots

      - name: Create tagged release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/DayNightPvP.jar

      - name: Deploy Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-distribution: temurin
          java-version: 17
          custom-command: 'mvn package javadoc:aggregate -pl :DayNightPvP'
          target-folder: javadoc
          project: maven
